name: self-hosted-env

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "MAIN" ]
  pull_request:
    branches: [ "MAIN" ]
  workflow_dispatch:

jobs:
  List_files:
    runs-on: self-hosted
    steps:
      - name: Display custom env variables
        run: for i in {1..10}; do echo "This is running an echo at:"; date +'%m/%d/%Y'; sleep 30; done
 
